/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polar-bear-deeb7f4add9f4c36abaacdb73ce3e553
Title: Polar Bear
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import Bear from     '../assets/3d/polar_bear.glb'

const Barnes = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(Bear)
  const { actions } = useAnimations(animations, group)
  const meshRef = useRef();
  const [hovered, setHovered] = useState(false)
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  }, [hovered])
  return (
    <group ref={group} {...props} dispose={null} position={[0.2, 0 ,0.3]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_30" rotation={[0, 2.4, 0]} scale={0.08}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    onPointerOver={() => setHovered(true)}
                    onPointerOut={() => setHovered(false)} 
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.polar}
                    skeleton={nodes.Object_7.skeleton}
                    morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
                  />
                  <group name="Object_0_29" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Barnes;
