/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TheMadraver (https://sketchfab.com/TheMadraver)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/captains-quarters-a5c54257755e47ccb47b5d8bc7482d7e
Title: Captain's Quarters
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Room from '../assets/3d/captains_quarters.glb'

const CaptinRoom = (props) => {
  const { nodes, materials } = useGLTF(Room)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-52.75, 36.021, -24.833]}
            rotation={[0, -1.008, 0]}
            scale={[0.659, 0.683, 0.904]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cylinder003_Material_#160_0'].geometry}
              material={materials.Material_160}
              position={[0, 0, -9.21]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_Bookcase_0.geometry}
            material={materials.Bookcase}
            position={[13.599, 40.42, 60.188]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf_Books1_0.geometry}
            material={materials.Books1}
            position={[6.475, 69.46, 60.753]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf002_Tilted_Books_0.geometry}
            material={materials.Tilted_Books}
            position={[1.819, 57.044, 60.755]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vase_Vase_0.geometry}
            material={materials.Vase}
            position={[4.502, 30.838, 61.261]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Globe_Globe_0.geometry}
            material={materials.Globe}
            position={[-98.222, 25.962, 41.348]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Globe_Frame_GlobeStand_0.geometry}
            material={materials.GlobeStand}
            position={[-98.297, 19.548, 41.4]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ClosedChest_ClosedChest_0.geometry}
            material={materials.ClosedChest}
            position={[-95.491, 8.889, -127.919]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk_Desk_0.geometry}
            material={materials.Desk}
            position={[-37.958, 16.521, 55.366]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RailingLeft_Banister_0.geometry}
            material={materials.Banister}
            position={[99.223, 26.252, -108.017]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OpenChest_OpenChest_0.geometry}
            material={materials.OpenChest}
            position={[-91.715, 11.672, 8.067]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Drawers_ChestDrawersMain_0.geometry}
            material={materials.ChestDrawersMain}
            position={[35.334, 24.104, -166.183]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseDrawer_LooseDrawer_0.geometry}
            material={materials.LooseDrawer}
            position={[27.31, 39.693, -175.432]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bed_Bed_0.geometry}
            material={materials.material}
            position={[-32.888, 18.671, -160.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StairRug_Stairs_0.geometry}
            material={materials.Stairs}
            position={[75.277, 8.153, -43.008]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pillow_Pillow_0.geometry}
            material={materials.Pillow}
            position={[-64.038, 18.037, -162.182]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Duvet_Duvet_0.geometry}
            material={materials.Duvet}
            position={[-28.98, 18.635, -160.951]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CurtainRailing_CurtainRail_0.geometry}
            material={materials.CurtainRail}
            position={[-144.282, 99.988, -43.026]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf001_Books1_0.geometry}
            material={materials.Books1}
            position={[-65.881, 63.99, -190.175]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate_Crate_0.geometry}
            material={materials.Crate}
            position={[79.265, 14.4, 47.493]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate001_Crate_0.geometry}
            material={materials.Crate}
            position={[78.874, 42.657, 49.843]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate002_Crate_0.geometry}
            material={materials.Crate}
            position={[120.185, 31.5, -124.322]}
            rotation={[-Math.PI / 2, 0, -1.222]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LongCrate_Large_Crate_0.geometry}
            material={materials.Large_Crate}
            position={[119.367, 53.054, 46.086]}
            rotation={[-Math.PI / 2, 0, Math.PI / 6]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OpenSmallCrate001_OpenCrate_0.geometry}
            material={materials.OpenCrate}
            position={[124.476, 52.021, -125.01]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack002_Sack_0.geometry}
            material={materials.Sack}
            position={[76.765, 2.417, -103.689]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OpenSmallCrate002_OpenCrate_0.geometry}
            material={materials.OpenCrate}
            position={[28.931, 8.118, -128.811]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf006_Books1_0.geometry}
            material={materials.Books1}
            position={[23.333, 32.859, 59.977]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack004_Sack_0.geometry}
            material={materials.Sack}
            position={[78.287, 16.997, -122.525]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack005_Sack_0.geometry}
            material={materials.Sack}
            position={[105.623, 34.128, 31.498]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel001_Barrel_0.geometry}
            material={materials.Barrel}
            position={[47.339, 17.498, 37.431]}
            rotation={[-Math.PI / 2, 0, 2.705]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OpenSmallCrate003_OpenCrate_0.geometry}
            material={materials.OpenCrate}
            position={[48.297, 41.375, 43.915]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CurtainRight001_Curtain_0.geometry}
            material={materials.Curtain}
            position={[-126.196, 52.574, 30.995]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf009_LongBooks_0.geometry}
            material={materials.LongBooks}
            position={[-58.375, 95.818, 70.439]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vase001_Vase_0.geometry}
            material={materials.Vase}
            position={[-55.993, 62.028, -192.264]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BirdCage_Birdcage_0.geometry}
            material={materials.Birdcage}
            position={[-16.038, 45.053, 59.019]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern_Candle_0.geometry}
            material={materials.Candle}
            position={[-79.536, 93.46, 62.189]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Table_Table_0.geometry}
            material={materials.Table}
            position={[-58.508, 17.623, -48.649]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel002_Barrel_0.geometry}
            material={materials.Barrel}
            position={[55.977, 17.077, -126.804]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern001_Candle_0.geometry}
            material={materials.Candle}
            position={[55.637, 93.46, 58.194]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern002_Candle_0.geometry}
            material={materials.Candle}
            position={[-79.536, 93.46, -148.871]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern003_Candle_0.geometry}
            material={materials.Candle}
            position={[55.637, 93.46, -144.831]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternHookClose001_WallHook_0.geometry}
            material={materials.WallHook}
            position={[55.558, 99.455, -147.538]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rug_Rug_0.geometry}
            material={materials.material_28}
            position={[-51.782, 0.118, -50.132]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf010_LongBooks_0.geometry}
            material={materials.LongBooks}
            position={[13.627, 44.934, 60.48]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf011_LongBooks_0.geometry}
            material={materials.LongBooks}
            position={[31.187, 64.51, -189.687]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf012_Tilted_Books_0.geometry}
            material={materials.Tilted_Books}
            position={[13.578, 64.031, -189.969]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Barrel003_Barrel_0.geometry}
            material={materials.Barrel}
            position={[79.555, 17.077, -142.863]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting001_PaintingV1_0.geometry}
            material={materials.PaintingV1}
            position={[-29.478, 71.028, 72.769]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting005_PaintingV2_0.geometry}
            material={materials.PaintingV2}
            position={[-50.527, 95.328, -196.692]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting007_PaintingV4_0.geometry}
            material={materials.PaintingV4}
            position={[115.687, 82.167, -149.803]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar4_BottleV2_0.geometry}
            material={materials.BottleV2}
            position={[40.036, 37.07, 48.822]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar1Low001_BottleVar1_0.geometry}
            material={materials.BottleVar1}
            position={[-43.083, 36.952, -80.946]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar1Low002_BottleVar1_0.geometry}
            material={materials.BottleVar1}
            position={[-12.207, 39.233, 45.391]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook002_LooseBookV2_0.geometry}
            material={materials.LooseBookV2}
            position={[-61.135, 35.838, -73.479]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook003_LooseBookV1_0.geometry}
            material={materials.LooseBookV1}
            position={[-48.57, 36.037, -17.807]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook004_LooseBookV2_0.geometry}
            material={materials.LooseBookV2}
            position={[-29.488, 33.958, 51.11]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook005_LooseBookV3_0.geometry}
            material={materials.LooseBookV3}
            position={[-29.487, 36.132, 51.123]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook006_LooseBookV3_0.geometry}
            material={materials.LooseBookV3}
            position={[-65.074, 1.191, -88.251]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Inkwell_Inkwell_0.geometry}
            material={materials.Inkwell}
            position={[-68.141, 38.043, -69.079]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DeskChair_Chair_0.geometry}
            material={materials.Chair}
            position={[-36.841, 19.443, 39.961]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door002_Door_0.geometry}
            material={materials.Door}
            position={[147.913, 63.268, 48.951]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BooksShelf013_Books1_0.geometry}
            material={materials.Books1}
            position={[23.057, 56.739, 60.753]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RailingLeft003_Banister_0.geometry}
            material={materials.Banister}
            position={[99.223, 26.252, 22.676]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternHookClose002_WallHook_0.geometry}
            material={materials.WallHook}
            position={[-79.561, 99.52, -151.672]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternHookClose003_WallHook_0.geometry}
            material={materials.WallHook}
            position={[-79.561, 99.52, 64.646]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LanternHookClose004_WallHook_0.geometry}
            material={materials.WallHook}
            position={[55.571, 99.52, 61.113]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting008_PaintingV3_0.geometry}
            material={materials.PaintingV3}
            position={[20.969, 76.52, -196]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting009_PaintingV1_0.geometry}
            material={materials.PaintingV1}
            position={[33.622, 16.297, -144.531]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Painting010_PaintingBase_0.geometry}
            material={materials.PaintingBase}
            position={[34.823, 15.194, -142.467]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar1Low003_BottleVar1_0.geometry}
            material={materials.BottleVar1}
            position={[61.077, 1.772, 37.569]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CurtainRight002_Curtain_0.geometry}
            material={materials.Curtain}
            position={[-126.196, 52.574, -121.488]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LooseBook007_Material_#158_0'].geometry}
            material={materials.Material_158}
            position={[39.512, 49.158, -155.263]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LooseBook008_LooseBookV3_0.geometry}
            material={materials.LooseBookV3}
            position={[33.593, 4.4, -129.645]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar005_BottleV2_0.geometry}
            material={materials.BottleV2}
            position={[42.423, 37.168, 46.533]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar006_BottleV2_0.geometry}
            material={materials.BottleV2}
            position={[45.895, 37.139, 45.642]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar007_BottleV2_0.geometry}
            material={materials.BottleV2}
            position={[41.141, 39.752, 48.54]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar1Low004_BottleVar1_0.geometry}
            material={materials.BottleVar1}
            position={[50.403, 36.952, 42.517]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BottleVar1Low005_BottleVar1_0.geometry}
            material={materials.BottleVar1}
            position={[48.843, 39.484, 50.595]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SidesAndFloor001_WallsAndFloor_0.geometry}
            material={materials.WallsAndFloor}
            position={[0.014, 69.676, -59.006]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 1.026]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door003_Door_0.geometry}
            material={materials.Door}
            position={[147.913, 63.268, -41.115]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Flag001_Flag_0.geometry}
            material={materials.Flag}
            position={[134.382, 68.371, -43.119]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

export default CaptinRoom;
